repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|json|md|yml|yaml)$
        exclude: ^(frontend/node_modules|backend/venv|\.git)

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx)$
        exclude: ^(frontend/node_modules|\.git)
        additional_dependencies:
          - eslint@^8.0.0
          - eslint-config-next@14.0.0
          - '@typescript-eslint/eslint-plugin@^6.0.0'
          - '@typescript-eslint/parser@^6.0.0'

  - repo: local
    hooks:
      - id: frontend-type-check
        name: Frontend Type Check
        entry: pnpm type-check
        language: system
        files: ^frontend/.*\.(ts|tsx)$
        pass_filenames: false

      - id: backend-lint
        name: Backend Lint
        entry: |
          cd backend
          black --check app/
          isort --check-only app/
          flake8 app/ --max-line-length=88 --extend-ignore=E203,W503
        language: system
        files: ^backend/.*\.py$
        pass_filenames: false

      - id: env-check
        name: Environment Check
        entry: pnpm check:env
        language: system
        pass_filenames: false
